# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      name: Set up JDK 1.8
      with:
        java-version: 1.8

    - run: chmod +x gradlew
      name: Grant execute permission for gradlew

    - run: ./gradlew build
      name: Build with Gradle

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and Push Docker Image
      with:
        image: rejux/spring-boot-gradle-ci-cd-sample
        tags: v1, latest
        registry: docker.io # the official Docker hub registry
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

